_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 75
                - 95
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 75
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.7
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
chunk_size:
    value: 0
is_recursive:
    value: false
is_semantic:
    value: true
method:
    value: local
model_name:
    value: intfloat/multilingual-e5-large-instruct
qa_pairs_count:
    value: 51
reranker_model:
    value: cross-encoder/ms-marco-MiniLM-L-6-v2
top_k:
    value: 10
use_reranker:
    value: true
